version: '3.7'

services:
  oauth2-proxy:
    image: quay.io/oauth2-proxy/oauth2-proxy:latest
    container_name: oauth2-proxy
    command:
      - --provider=oidc
      - --login-url=https://casdoor.quelleo.com/login
      - --redeem-url=https://casdoor.quelleo.com/oauth2/token
      - --oidc-issuer-url=https://casdoor.quelleo.com
      - --client-id=e67af7eba2ba979f317d
      - --client-secret=5a618ccc37d4cd3b64ae88cd66931b408e808f51
      - --cookie-secret=7Njvw3JDeq8tSwYgMziheQ==
      - --cookie-domain=.quelleo.com
      - --redirect-url=https://auth.quelleo.com/oauth2/callback
      - --email-domain=*
      - --scope=openid email profile
      - --skip-provider-button=true
      - --skip-auth-strip-headers=true
      - --auth-logging=true
      - --set-xauthrequest=true
      - --reverse-proxy=true
      - --proxy-prefix=/oauth2
      - --upstream=static://200
      - --http-address=0.0.0.0:4180
      - --insecure-oidc-skip-issuer-verification=false
    ports:
      - "4180:4180"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.oauth2.rule=Host(`auth.quelleo.com`)"
      - "traefik.http.routers.oauth2.entrypoints=websecure"
      - "traefik.http.routers.oauth2.tls=true"
      - "traefik.http.routers.oauth2.tls.certresolver=myresolver"
      - "traefik.http.services.oauth2.loadbalancer.server.port=4180"
    networks:
      - traefik-network
    restart: unless-stopped

networks:
  traefik-network:
    external: true

